<?php

namespace AppBundle\Repository;

/**
 * ObjectsLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectsLogRepository extends \Doctrine\ORM\EntityRepository
{
}
