<?php

namespace AppBundle\Repository;

/**
 * StatisticsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatisticsRepository extends \Doctrine\ORM\EntityRepository
{
}
